/**
 * questkit-worker-api — REST + SSE + Durable Objects + Workers AI.
 *
 * Phase 1 scaffold: only GET /v1/health was wired. Phase 2 (TASK-006..011)
 * brought in /v1/auth, /v1/events, /v1/missions, /v1/balance, /v1/campaigns,
 * /v1/sse, and the real RateLimiter + SSEHub Durable Objects.
 *
 * The Env type is generated by `wrangler types` into worker-configuration.d.ts
 * (gitignored). Run `pnpm cf-typegen` after install. Secret string types are
 * augmented in src/env.d.ts because secrets aren't yet inferred from the
 * generated d.ts at scaffold time.
 */
import { Hono } from "hono";
import { HTTPException } from "hono/http-exception";
import authRouter from "./routes/auth";
import balanceRouter from "./routes/balance";
import campaignsRouter from "./routes/campaigns";
import eventsRouter from "./routes/events";
import missionsRouter from "./routes/missions";
import recommendationsRouter from "./routes/recommendations";
import sseRouter from "./routes/sse";

const app = new Hono<{ Bindings: Env }>();

/**
 * Liveness probe. Phase 1 smoke test — wired to a deploy verification step.
 * Returns a static version + the build's git SHA if injected via env.
 */
app.get("/v1/health", (c) => {
  return c.json({
    ok: true,
    version: "0.1.0",
    commit: c.env.GIT_SHA ?? "dev",
  });
});

/**
 * /v1/auth — JWT minting. Intentionally unauthenticated; downstream
 * /v1/events (TASK-008) and other routes will mount `requireAuth` from
 * `./auth/middleware`.
 */
app.route("/v1/auth", authRouter);

/**
 * /v1/balance — user wallet read (TASK-010). JWT-protected.
 */
app.route("/v1/balance", balanceRouter);

/**
 * /v1/campaigns — campaign read (TASK-010). JWT-protected.
 */
app.route("/v1/campaigns", campaignsRouter);

/**
 * /v1/events — event ingestion. JWT-protected (mounted middleware in the
 * router itself). Mounted AFTER /v1/auth so an unauthenticated client can
 * still mint a token before firing events.
 */
app.route("/v1/events", eventsRouter);

/**
 * /v1/missions — mission read + atomic claim (TASK-010). JWT-protected.
 */
app.route("/v1/missions", missionsRouter);

/**
 * /v1/recommendations — AI-powered mission recommendations (TASK-017).
 * JWT-protected. Backed by Workers AI (`@cf/meta/llama-3.1-8b-instruct-fast`)
 * with KV-cached results (1h TTL per user).
 */
app.route("/v1/recommendations", recommendationsRouter);

/**
 * /v1/sse — live SDKUpdate fanout (TASK-011). JWT-protected. The /updates
 * sub-route opens a long-lived text/event-stream proxied through the user's
 * per-user SSEHub DO.
 */
app.route("/v1/sse", sseRouter);

/**
 * Centralised error handler.
 *
 * `HTTPException` is the Hono-idiomatic way for middleware (e.g. `requireAuth`)
 * and route handlers to short-circuit with a known status. We delegate to
 * `err.getResponse()` so the HTTP status + message body are preserved (e.g.
 * `requireAuth` throws HTTPException(401, { message: "missing_token" })`).
 *
 * Anything that's not an HTTPException is unexpected — logged for the
 * operator (Workers Logs / observability enabled in wrangler.jsonc) and
 * returned as a generic 500. We do NOT echo the underlying message because
 * it may contain implementation detail.
 *
 * Touched by TASK-008 (events-route-builder, teammate B) — the original
 * handler returned 500 unconditionally, which collided with the auth
 * middleware's HTTPException path. Flagged in the report.
 */
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    return err.getResponse();
  }
  console.error("[api] unhandled", err);
  return c.json({ error: "internal_error" }, 500);
});

export default app;

/**
 * Durable Object class exports.
 *
 * `wrangler.jsonc` references these classes by string name in both
 * `migrations[].new_sqlite_classes` and `durable_objects.bindings`. The
 * class names MUST remain `RateLimiter` and `SSEHub` exactly. We re-export
 * here from `./durable/*` so the worker bundle's exports include the class
 * symbols — wrangler discovers DO classes by bundle export.
 *
 * Until TASK-011 these were 501 stubs defined inline; now they're full
 * implementations living in their own modules.
 */
export { RateLimiter } from "./durable/rate-limiter";
export { SSEHub } from "./durable/sse-hub";
