/**
 * questkit-worker-api — REST + SSE + Durable Objects + Workers AI.
 *
 * Phase 1 scaffold: only GET /v1/health is wired. Routes, auth, rule engine,
 * Durable Object internals, SSE, and AI recommendations all land in Phase 2+.
 *
 * The Env type is generated by `wrangler types` into worker-configuration.d.ts
 * (gitignored). Run `pnpm cf-typegen` after install. Secret string types are
 * augmented in src/env.d.ts because secrets aren't yet inferred from the
 * generated d.ts at scaffold time.
 */
import { Hono } from "hono";

const app = new Hono<{ Bindings: Env }>();

/**
 * Liveness probe. Phase 1 smoke test — wired to a deploy verification step.
 * Returns a static version + the build's git SHA if injected via env.
 */
app.get("/v1/health", (c) => {
  return c.json({
    ok: true,
    version: "0.1.0",
    commit: c.env.GIT_SHA ?? "dev",
  });
});

/**
 * Centralised error handler. Logs to Workers Logs (observability enabled in
 * wrangler.jsonc) and returns a generic 500. Per-route handlers should throw
 * HTTPException for known client errors; anything that reaches here is
 * unexpected.
 */
app.onError((err, c) => {
  console.error("[api] unhandled", err);
  return c.json({ error: "internal_error" }, 500);
});

export default app;

/**
 * Durable Object: per-JWT sliding-window rate limiter.
 * STUB — full implementation in TASK-011 (Phase 2). The class export is
 * required at deploy time because wrangler.jsonc declares the class in
 * `migrations[].new_sqlite_classes` and `durable_objects.bindings`.
 */
export class RateLimiter {
  constructor(
    public state: DurableObjectState,
    public env: Env,
  ) {}

  async fetch(_request: Request): Promise<Response> {
    return new Response("not implemented", { status: 501 });
  }
}

/**
 * Durable Object: per-user SSE fanout hub.
 * STUB — full implementation in TASK-011 (Phase 2). Same reason as above:
 * class export must exist for the wrangler config to validate / deploy.
 */
export class SSEHub {
  constructor(
    public state: DurableObjectState,
    public env: Env,
  ) {}

  async fetch(_request: Request): Promise<Response> {
    return new Response("not implemented", { status: 501 });
  }
}
