/**
 * questkit-worker-api — REST + SSE + Durable Objects + Workers AI + RPC.
 *
 * Phase 1 scaffold: only GET /v1/health was wired. Phase 2 (TASK-006..011)
 * brought in /v1/auth, /v1/events, /v1/missions, /v1/balance, /v1/campaigns,
 * /v1/sse, and the real RateLimiter + SSEHub Durable Objects. TASK-022
 * (Phase 4) added the `ApiService` WorkerEntrypoint RPC class so the
 * webhook-consumer worker can ingest events directly without HTTP roundtrip.
 *
 * The Env type is generated by `wrangler types` into worker-configuration.d.ts
 * (gitignored). Run `pnpm cf-typegen` after install. Secret string types are
 * augmented in src/env.d.ts because secrets aren't yet inferred from the
 * generated d.ts at scaffold time.
 */
import type { Event } from "@questkit/types";
import { WorkerEntrypoint } from "cloudflare:workers";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import authRouter from "./routes/auth";
import balanceRouter from "./routes/balance";
import campaignsRouter from "./routes/campaigns";
import demoRouter from "./routes/demo";
import eventsRouter from "./routes/events";
import missionsRouter from "./routes/missions";
import recommendationsRouter from "./routes/recommendations";
import sseRouter from "./routes/sse";
import { ingestEventCore } from "./services/ingest";

const app = new Hono<{ Bindings: Env }>();

/**
 * Permissive CORS — per plan.md §5: the SDK is designed to run on any host
 * (React component library + vanilla embed + first-party demo / docs / play),
 * so the API accepts requests from any origin. The JWT (HS256, JTI denylist)
 * is the security boundary, not the Origin header. `/v1/auth/token` itself
 * carries the appSecret in the body and is intended to be called server-side
 * only — but allowing cross-origin POST keeps proxy-based mint flows like
 * the demo's `/api/token` from breaking when the demo and api live on
 * different hostnames.
 */
app.use(
  "*",
  cors({
    origin: "*",
    allowMethods: ["GET", "POST", "OPTIONS"],
    allowHeaders: ["Content-Type", "Authorization", "Idempotency-Key"],
    exposeHeaders: ["X-Idempotent-Replay"],
    maxAge: 86400,
    credentials: false,
  }),
);

/**
 * Liveness probe. Phase 1 smoke test — wired to a deploy verification step.
 * Returns a static version + the build's git SHA if injected via env.
 */
app.get("/v1/health", (c) => {
  return c.json({
    ok: true,
    version: "0.1.13",
    commit: c.env.GIT_SHA ?? "dev",
  });
});

/**
 * /v1/auth — JWT minting. Intentionally unauthenticated; downstream
 * /v1/events (TASK-008) and other routes will mount `requireAuth` from
 * `./auth/middleware`.
 */
app.route("/v1/auth", authRouter);

/**
 * /v1/balance — user wallet read (TASK-010). JWT-protected.
 */
app.route("/v1/balance", balanceRouter);

/**
 * /v1/campaigns — campaign read (TASK-010). JWT-protected.
 */
app.route("/v1/campaigns", campaignsRouter);

/**
 * /v1/demo — demo-user utilities (Phase 8 / TASK-003). JWT-protected, with
 * an additional gate requiring `kind: "demo"` on the JWT AND a `demo_`
 * userId prefix. POST /v1/demo/reset wipes the caller's `mission_progress`,
 * `balances`, `events`, and per-user KV scratch space in one atomic D1
 * batch + a best-effort KV sweep.
 */
app.route("/v1/demo", demoRouter);

/**
 * /v1/events — event ingestion. JWT-protected (mounted middleware in the
 * router itself). Mounted AFTER /v1/auth so an unauthenticated client can
 * still mint a token before firing events.
 */
app.route("/v1/events", eventsRouter);

/**
 * /v1/missions — mission read + atomic claim (TASK-010). JWT-protected.
 */
app.route("/v1/missions", missionsRouter);

/**
 * /v1/recommendations — AI-powered mission recommendations (TASK-017).
 * JWT-protected. Backed by Workers AI (`@cf/meta/llama-3.1-8b-instruct-fast`)
 * with KV-cached results (1h TTL per user).
 */
app.route("/v1/recommendations", recommendationsRouter);

/**
 * /v1/sse — live SDKUpdate fanout (TASK-011). JWT-protected. The /updates
 * sub-route opens a long-lived text/event-stream proxied through the user's
 * per-user SSEHub DO.
 */
app.route("/v1/sse", sseRouter);

/**
 * Centralised error handler.
 *
 * `HTTPException` is the Hono-idiomatic way for middleware (e.g. `requireAuth`)
 * and route handlers to short-circuit with a known status. We delegate to
 * `err.getResponse()` so the HTTP status + message body are preserved (e.g.
 * `requireAuth` throws HTTPException(401, { message: "missing_token" })`).
 *
 * Anything that's not an HTTPException is unexpected — logged for the
 * operator (Workers Logs / observability enabled in wrangler.jsonc) and
 * returned as a generic 500. We do NOT echo the underlying message because
 * it may contain implementation detail.
 *
 * Touched by TASK-008 (events-route-builder, teammate B) — the original
 * handler returned 500 unconditionally, which collided with the auth
 * middleware's HTTPException path. Flagged in the report.
 */
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    return err.getResponse();
  }
  console.error("[api] unhandled", err);
  return c.json({ error: "internal_error" }, 500);
});

export default app;

/**
 * Durable Object class exports.
 *
 * `wrangler.jsonc` references these classes by string name in both
 * `migrations[].new_sqlite_classes` and `durable_objects.bindings`. The
 * class names MUST remain `RateLimiter` and `SSEHub` exactly. We re-export
 * here from `./durable/*` so the worker bundle's exports include the class
 * symbols — wrangler discovers DO classes by bundle export.
 *
 * Until TASK-011 these were 501 stubs defined inline; now they're full
 * implementations living in their own modules.
 */
export { RateLimiter } from "./durable/rate-limiter";
export { SSEHub } from "./durable/sse-hub";

/**
 * `ApiService` — typed RPC entrypoint for trusted internal callers.
 *
 * The webhook-consumer worker (TASK-022) binds this entrypoint via its
 * `services[].entrypoint` config and invokes `ingestEvent(event)` directly,
 * skipping HTTP, JWT signing, and rate-limit checks. The consumer is a
 * trusted internal worker; rate-limiting at this layer would only protect
 * against runaway internal loops, which the queue's own retry/DLQ already
 * bounds.
 *
 * Idempotency still applies: the relay normaliser sets
 * `Event.idempotencyKey = "evt_${rawPayload.id}"` so duplicate queue
 * deliveries (CF Queues is at-least-once) collapse via the same KV +
 * partial-unique-index defence used by the HTTP route.
 *
 * Response shape: `{ accepted, missionsUpdated[] }`. We deliberately omit
 * `eventId` from the RPC envelope because the consumer doesn't need to
 * thread it back to Stripe; if a future caller needs it, add a sibling
 * method rather than mutating this one (RPC interfaces are wire contracts).
 *
 * Per cloudflare/workers-sdk#8902 the cross-worker `wrangler types`
 * generator may not infer RPC method signatures on the consumer side. The
 * consumer redeclares the shape in its own `env.d.ts` as a workaround.
 */
export class ApiService extends WorkerEntrypoint<Env> {
  async ingestEvent(
    event: Event,
  ): Promise<{ accepted: boolean; missionsUpdated: string[] }> {
    const body = {
      userId: event.userId,
      name: event.name,
      payload: event.payload,
      timestamp: event.timestamp,
      ...(event.idempotencyKey !== undefined
        ? { idempotencyKey: event.idempotencyKey }
        : {}),
    };
    // `this.ctx.waitUntil` lets the SSE broadcast fan-out (inside
    // `ingestEventCore`) run detached from the RPC response — same fix as
    // the HTTP route. See Phase 8 / v0.1.4 TASK-001.
    const result = await ingestEventCore(this.env, body, {
      waitUntil: (p) => this.ctx.waitUntil(p),
    });
    return { accepted: true, missionsUpdated: result.missionsUpdated };
  }
}
