/**
 * HS256 JWT primitives using Web Crypto `SubtleCrypto` — zero external deps.
 *
 * Why hand-roll instead of `hono/jwt` or `jose`?
 *   - hono/jwt re-implements the same maths with a couple extra layers; this
 *     file is the minimum honest surface and lets us own the verify path
 *     (the route middleware needs to add a KV-denylist check that wraps
 *     `verify`, and threading our own JTI through is cleaner if we own the
 *     primitive).
 *   - jose is excellent but ships ~30 KB of code for features we don't use
 *     (RSA, EdDSA, JWE, JWK). Web Crypto HMAC-SHA256 is one `crypto.subtle`
 *     call per side; the size win matters for cold-start times.
 *
 * Security notes:
 *   - HMAC-SHA256 with a ≥ 32-byte secret. `JWT_SECRET` is generated by
 *     `openssl rand -base64 48` per `.dev.vars.example`, so callers in
 *     practice pass 64 chars of base64 (48 bytes pre-decode → 64 chars
 *     post-encode). We do NOT base64-decode the secret — we use the literal
 *     UTF-8 bytes as the HMAC key. This is consistent with most JWT libraries
 *     and the security analysis (the secret's entropy is what matters; the
 *     encoding is irrelevant).
 *   - `crypto.subtle.verify` is timing-safe by spec. We use it directly on
 *     the recomputed signature rather than `===`-comparing strings.
 *   - `exp` is enforced strictly: `exp > now` must hold. No leeway window —
 *     the SDK is expected to refresh well before expiry.
 */

/**
 * Canonical JWT payload for QuestKit. We keep this minimal:
 *   - `sub`  user id (opaque to QuestKit; the host issues it)
 *   - `iat`  issued-at, seconds since epoch
 *   - `exp`  expiry,    seconds since epoch
 *   - `jti`  unique JWT id — used as the denylist key in KV (per plan §5)
 *   - `kind` optional capability marker. Today only "demo" is recognised,
 *     used by `/v1/demo/reset` to gate the dangerous data-wipe endpoint
 *     (Phase 8 / TASK-003). Tokens minted via the regular path omit this
 *     field entirely.
 *
 * No `iss`/`aud` because QuestKit is single-issuer; no extra fields because
 * downstream middleware only needs `sub`, `jti`, and (now) `kind`.
 */
export interface JwtPayload {
  sub: string;
  iat: number;
  exp: number;
  jti: string;
  kind?: "demo";
}

/**
 * Failure modes from `verify`. The `code` is what bubbles to the middleware
 * which translates it into an HTTP error message; we keep the codes ABI-stable
 * so any future client-facing telemetry has consistent strings.
 */
export type JwtErrorCode = "expired" | "invalid_signature" | "malformed";

export class JwtError extends Error {
  override name = "JwtError";
  constructor(
    public code: JwtErrorCode,
    message?: string,
  ) {
    super(message ?? code);
  }
}

const HEADER_B64URL = base64urlEncode(
  new TextEncoder().encode(JSON.stringify({ alg: "HS256", typ: "JWT" })),
);

/**
 * Produces a JWS-Compact-Serialization HS256 token:
 *   base64url(header) + "." + base64url(payload) + "." + base64url(sig)
 *
 * The header is fixed (`{alg:"HS256",typ:"JWT"}`) so we precompute its b64url
 * encoding at module load — saves a few microseconds per mint without sacrificing
 * any clarity.
 */
export async function sign(
  payload: JwtPayload,
  secret: string,
): Promise<string> {
  const payloadB64 = base64urlEncode(
    new TextEncoder().encode(JSON.stringify(payload)),
  );
  const signingInput = `${HEADER_B64URL}.${payloadB64}`;
  const key = await importHmacKey(secret, ["sign"]);
  const sigBytes = new Uint8Array(
    await crypto.subtle.sign(
      "HMAC",
      key,
      new TextEncoder().encode(signingInput),
    ),
  );
  return `${signingInput}.${base64urlEncode(sigBytes)}`;
}

/**
 * Verifies token integrity (timing-safe via `crypto.subtle.verify`) and that
 * `exp > now`. Returns the decoded payload on success; throws `JwtError` with
 * a discriminated code on every failure path.
 *
 * Order of checks:
 *   1) structural (3 segments)        → malformed
 *   2) payload decodes to valid JSON  → malformed
 *   3) signature verifies             → invalid_signature
 *   4) exp > now                      → expired
 *
 * We check signature BEFORE expiry on purpose — an attacker who can craft a
 * not-yet-expired forgery would otherwise learn about the expiry check via
 * timing. With this ordering the signature check fails first regardless of
 * `exp`, so timing is determined by HMAC compute + base64 only.
 */
export async function verify(
  token: string,
  secret: string,
): Promise<JwtPayload> {
  const parts = token.split(".");
  if (parts.length !== 3 || parts.some((p) => p.length === 0)) {
    throw new JwtError("malformed", "token must be 3 non-empty segments");
  }
  const [headerB64, payloadB64, sigB64] = parts as [string, string, string];

  // Decode the payload first so we have something to return; if any of these
  // throw we surface `malformed`.
  let payload: JwtPayload;
  try {
    const payloadBytes = base64urlDecode(payloadB64);
    payload = JSON.parse(new TextDecoder().decode(payloadBytes)) as JwtPayload;
  } catch {
    throw new JwtError("malformed", "payload not base64url-encoded JSON");
  }
  if (
    typeof payload !== "object" ||
    payload === null ||
    typeof payload.sub !== "string" ||
    typeof payload.iat !== "number" ||
    typeof payload.exp !== "number" ||
    typeof payload.jti !== "string"
  ) {
    throw new JwtError("malformed", "payload missing required fields");
  }

  let sigBytes: Uint8Array;
  try {
    sigBytes = base64urlDecode(sigB64);
  } catch {
    throw new JwtError("malformed", "signature not base64url");
  }

  const key = await importHmacKey(secret, ["verify"]);
  const ok = await crypto.subtle.verify(
    "HMAC",
    key,
    sigBytes,
    new TextEncoder().encode(`${headerB64}.${payloadB64}`),
  );
  if (!ok) throw new JwtError("invalid_signature", "HMAC verify failed");

  const now = Math.floor(Date.now() / 1000);
  if (payload.exp <= now) {
    throw new JwtError("expired", `exp ${payload.exp} <= now ${now}`);
  }

  return payload;
}

// -----------------------------------------------------------------------------
// internal helpers
// -----------------------------------------------------------------------------

// Workers types declare `KeyUsage` only as part of the DOM lib. We narrow the
// union explicitly so this file compiles under `lib: ES2023` without dragging
// the DOM types in (which would shadow some Workers globals).
type HmacKeyUsage = "sign" | "verify";

async function importHmacKey(
  secret: string,
  usages: HmacKeyUsage[],
): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    usages,
  );
}

/**
 * base64url = base64 with `+ → -`, `/ → _`, no padding. Workers runtime has
 * globalThis.btoa for the base64 step; we operate on a binary string built
 * from the byte array (the canonical pattern; using `btoa` directly on a
 * UTF-8 string would mangle anything > 0x7F, hence the manual byte-stringify).
 */
function base64urlEncode(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  const b64 = btoa(bin);
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function base64urlDecode(input: string): Uint8Array {
  const b64 = input.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
  const bin = atob(padded);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
